Adding new terminology
VRK-YTI/yti-terminology-ui pull request #124
Opened 2022-04-06 11:22 UTC by topirissanen-atoz

2022-04-08 06:28 UTC, kkyttala requested changes

2022-04-08 06:28 UTC, kkyttala commented on src/common/components/new-terminology/index.tsx
> +  }
What is the purpose of this check? Users with other roles, like terminology_editor are also allowed to create new terminologies

2022-04-08 06:28 UTC, kkyttala commented on src/common/components/new-terminology/info-file.tsx
> +          <Text smallScreen>Sallitut tiedostomuodot on: xlsx</Text>
should this text be localized (also at line 70)

2022-04-08 06:28 UTC, kkyttala commented on src/common/components/new-terminology/missing-info-alert.tsx
> +    ) {
contact and description are not mandatory information, but prefLabel should be mandatory

2022-04-08 09:47 UTC, kkyttala commented on src/common/components/new-terminology/language-selector.tsx
> +  ];
Application should support other languages too. Ideally we could utilize codelists for this but maybe it's an other feature https://koodistot.suomi.fi/codescheme;registryCode=interoperabilityplatform;schemeCode=languagecodes

2022-04-11 04:36 UTC, topirissanen-atoz commented on src/common/components/new-terminology/index.tsx
> +  }
Function for role checking will be added in https://github.com/VRK-YTI/yti-terminology-ui/pull/125

2022-04-11 04:36 UTC, topirissanen-atoz commented on src/common/components/new-terminology/language-selector.tsx
> +  ];
This is will be implemented later

2022-04-19 06:39 UTC, topirissanen-atoz commented on src/common/components/new-terminology/missing-info-alert.tsx
> +    ) {
Contact has been changed to be optional.
Description variable includes both prefLabel as well as descriptive information about terminology. This checks only that prefLabel is included in the provided information.

2022-04-19 09:21 UTC, jukkah commented on public/locales/fi/admin.json
> +  "allowed-file-formats": "Sallitut tiedostomuodot on:",
Grammar note: use either "Sallitut tiedostomuodot:" or "Sallitut tiedostomuodot ovat:". The first matches better with English translation.

2022-04-20 07:06 UTC, jukkah approved these changes

2022-04-20 08:56 UTC, kkyttala approved these changes

2022-04-20 11:29 UTC, jukkah approved these changes

2022-04-20 11:30 UTC, merged