Yti 1925 editor and modifier bugfix
VRK-YTI/yti-terminology-ui pull request #160
Opened 2022-06-08 08:54 UTC by topirissanen-atoz

2022-06-09 06:26 UTC, jukkah approved these changes

2022-06-09 10:56 UTC, kkyttala requested changes

2022-06-09 10:56 UTC, kkyttala commented on src/pages/terminology/[terminologyId].tsx
> +    store.dispatch(
[terminologyId].tsx should also have JSESSIONID, because there is the same logic displaying creator and modifier information

2022-06-10 08:58 UTC, kkyttala submitted a review, later dismissed

2022-06-13 05:36 UTC, jukkah submitted a review, later dismissed

2022-06-15 08:12 UTC, kkyttala approved these changes

2022-06-15 10:37 UTC, jukkah approved these changes

2022-06-16 04:06 UTC, merged