Removed Alert if user not subscribed
VRK-YTI/yti-terminology-ui pull request #177
Opened 2022-08-08 09:15 UTC by topirissanen-atoz

2022-08-09 06:02 UTC, jukkah requested changes

2022-08-09 06:02 UTC, jukkah commented on public/locales/en/common_old.json
> +  "email-subscription-unsubscribed": "Email notifications off",
In this situation, all changes to the three `{fi|sv|en}/common_old.json` files can be ignored. This `email-subscription-unsubscribed` is truly removed and we don't need it anymore.

2022-08-09 07:40 UTC, tomiviljanen approved these changes

2022-08-10 10:17 UTC, jukkah approved these changes

2022-08-10 10:34 UTC, merged