Added support for visualizing vocabs of type other
VRK-YTI/yti-terminology-ui pull request #183
Opened 2022-08-10 08:13 UTC by topirissanen-atoz

2022-08-10 09:49 UTC, jukkah requested changes

2022-08-10 09:49 UTC, jukkah commented on public/locales/en/common_old.json
> +  "terminology-search-results-terminology": "Terminology",
Should these unused translation keys be removed from all three languages?

2022-08-10 09:49 UTC, jukkah commented on src/common/utils/translation-helpers.ts
> +  type: string | undefined,
I think undefined should not be probably allowed here. This way it will return "Terminology type undefined". But if some vocabulary doesn't have the type at all it is probably terminological vocabulary not "terminology type undefined" (like in the missing status case).

2022-08-10 09:49 UTC, jukkah commented on src/common/utils/translation-helpers.ts
> +      return t('TERMINOLOGICAL_VOCABULARY', { ns: 'common' });
I'd like to use nesting here to group these translation keys in the JSON files. E.g. `terminology-type.terminological-vocabulary`.

2022-08-11 05:21 UTC, tomiviljanen approved these changes

2022-08-11 05:30 UTC, jukkah approved these changes

2022-08-11 05:34 UTC, merged