YTI-2022 term and concept missing properties
VRK-YTI/yti-terminology-ui pull request #223
Opened 2022-09-05 09:28 UTC by kkyttala

- Add subject area to concept form
- Possibility to add several sources and editorial notes for concept and term

<img width="697" alt="Screenshot 2022-09-05 at 12 23 21" src="https://user-images.githubusercontent.com/16885816/188416018-8e5f8981-163e-474c-9ca0-9bc0dd1928cb.png">

<img width="797" alt="Screenshot 2022-09-05 at 12 27 55" src="https://user-images.githubusercontent.com/16885816/188416795-7f72f607-6ef2-4fd1-b4d0-b3fdb7e2594c.png">

2022-09-06 05:49 UTC, jukkah requested changes

2022-09-06 05:49 UTC, jukkah commented on src/common/components/term-modal/index.tsx
> +              <li key={`term-source-${idx}`}>{v}</li>
Key must be unique inside of this map. So no need to use string interpolation. Also index based keys are not considered good practice in React. It's better to use some kind of ID or in this case just `v`. So the result would look like `key={v}`.

2022-09-06 05:49 UTC, jukkah commented on src/common/components/term-modal/term-expander.tsx
> +                      <li key={`${value}-${idx}`}>{value}</li>
Same here.

2022-09-06 05:49 UTC, jukkah commented on src/modules/concept/administrative-details-expander.tsx
> +              <li key={`${note}-${idx}`}>{note.value}</li>
And here.

2022-09-06 05:49 UTC, jukkah commented on src/modules/concept/diagrams-and-sources-expander.tsx
> +              <li key={`${source}-${idx}`}>{source.value}</li>
And here.

2022-09-06 05:49 UTC, tomiviljanen submitted a review, later dismissed

2022-09-08 05:59 UTC, tomiviljanen approved these changes

2022-09-08 06:38 UTC, jukkah approved these changes

2022-09-08 07:44 UTC, merged