Yti 2108 permission bugfix
VRK-YTI/yti-terminology-ui pull request #245
Opened 2022-09-20 05:30 UTC by topirissanen-atoz

2022-09-20 07:15 UTC, tomiviljanen requested changes

2022-09-20 07:15 UTC, tomiviljanen commented on src/modules/concept/index.tsx
> +            targetOrganization: terminology?.references.contributor?.[0].id,
Won't this allow only the first contributor to edit the concept?
There was a recent change to allow multiple contributors per terminology.

2022-09-20 08:39 UTC, topirissanen-atoz commented on src/modules/concept/index.tsx
> +            targetOrganization: terminology?.references.contributor?.[0].id,
Good thing to point out! I will make some changes to that

2022-09-20 11:31 UTC, tomiviljanen approved these changes

2022-09-21 06:00 UTC, kkyttala approved these changes

2022-09-21 08:20 UTC, merged