API call delete key is used when deleting term
VRK-YTI/yti-terminology-ui pull request #258
Opened 2022-09-28 11:14 UTC by topirissanen-atoz

2022-09-29 05:49 UTC, tomiviljanen requested changes

2022-09-29 05:49 UTC, tomiviljanen commented on src/modules/edit-concept/generate-concept.tsx
> +  console.log(initialValue);
forgotten console.log?

2022-09-29 07:55 UTC, tomiviljanen approved these changes

2022-09-30 07:29 UTC, kkyttala approved these changes

2022-09-30 07:33 UTC, merged