Copied from information added
VRK-YTI/yti-terminology-ui pull request #273
Opened 2022-10-11 06:10 UTC by topirissanen-atoz

2022-10-11 07:35 UTC, kkyttala commented
The value of origin property should also be included to the payload when modifying terminology. Otherwise it will be overwritten

2022-10-11 07:36 UTC, kkyttala requested changes
https://github.com/VRK-YTI/yti-terminology-ui/pull/273#issuecomment-1274222847

2022-10-11 09:46 UTC, tomiviljanen requested changes

2022-10-11 09:46 UTC, tomiviljanen commented on src/modules/new-terminology/generate-new-terminology.tsx
> +  console.log(postData);
console.log

2022-10-11 12:34 UTC, kkyttala approved these changes

2022-10-12 05:36 UTC, tomiviljanen approved these changes

2022-10-12 10:18 UTC, merged