Rearrenged components in terminology expander
VRK-YTI/yti-terminology-ui pull request #281
Opened 2022-10-17 05:30 UTC by topirissanen-atoz

2022-10-17 07:00 UTC, tomiviljanen submitted a review, later dismissed

2022-10-17 12:43 UTC, kkyttala requested changes

2022-10-17 12:43 UTC, kkyttala commented on src/common/components/info-dropdown/info-expander.tsx
> +              title={'Sanaston toiminnot'}
Should translated value be used?

2022-10-17 12:43 UTC, kkyttala commented on src/common/components/info-dropdown/info-expander.tsx
> +              title={'Käsitteiden toiminnot'}
Should translated value be used?

2022-10-20 07:08 UTC, kkyttala approved these changes

2022-10-21 03:44 UTC, merged