Yti 1605 reusable components
VRK-YTI/yti-terminology-ui pull request #38
Opened 2021-12-10 06:29 UTC by topirissanen-atoz

Updated components to be more general and fixed styles.

- Filter has been broken down into smaller components in filter-folder
- Updated terminology-search-slice to add needed functionality for Filter to work on Search-page.
- Removed bunch of old code from /terminology-search and /vocabulary - both now only have slice files.

Search-page without any additional filters.
![image](https://user-images.githubusercontent.com/82932696/145527166-fbbf4ece-e7ba-4ec7-a060-994e851e11ce.png)

Search-page with additional filters.
![image](https://user-images.githubusercontent.com/82932696/145527238-1a7f0dd4-a233-4c6d-aa80-ed53a55eef6a.png)

Terminology-page without any additional filters.
![image](https://user-images.githubusercontent.com/82932696/145527371-62cc26e9-ab3c-484e-8a17-c51fcdeaecce.png)

Terminology-page with additional filters.
![image](https://user-images.githubusercontent.com/82932696/145527442-2753ab8d-06ce-4991-b6bb-7b5ea0955372.png)

Terminology-page information.
![image](https://user-images.githubusercontent.com/82932696/145527496-933b220f-9146-4ef9-b564-39f041447b3f.png)

2021-12-13 06:43 UTC, jukkah requested changes

2021-12-13 06:43 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +        {JSON.stringify(filter) !== JSON.stringify(vocabularyEmptyState.filter) &&
Note that `JSON.stringify({ a: 1, b: 1 }) !== JSON.stringify({ b: 1, a: 1 })`. Is it possible that these object were constructed in different order?

2021-12-13 06:43 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +            JSON.stringify({ ...filter, infoDomains: {} }) !== JSON.stringify(initialState.filter)
Same here.

2021-12-13 06:43 UTC, jukkah commented on src/common/components/search-results/search-results.tsx
> +                      <span dangerouslySetInnerHTML={{
Why dangerouslySetInnerHTML? I can't see why normal conditional rendering would not work.

2021-12-15 06:28 UTC, jukkah approved these changes

2021-12-15 06:28 UTC, jukkah commented on src/modules/terminology-search/index.tsx
> +                  isSmall={breakPoints.isSmall}
This could also be moved to Pagination component itself.

2021-12-16 06:57 UTC, jukkah approved these changes

2021-12-16 07:00 UTC, merged

2021-12-16 07:30 UTC, urhot commented on src/common/components/filter/checkbox-area.tsx
> +    let retVal: CheckboxProps['filter'] | undefined;
I think null would be more appropriate here:

```ts
let retVal: CeckboxProps['filter'] | null = null;
```