Yti 1615 filter mobile version
VRK-YTI/yti-terminology-ui pull request #43
Opened 2021-12-28 06:04 UTC by topirissanen-atoz

2021-12-28 08:28 UTC, urhot commented on src/common/components/filter/filter.tsx
> +    if (isModal) {
for cleaner code:

```typescript
if (!isModal) {
  return null;
}

return ...
```

2021-12-29 08:14 UTC, kkyttala approved these changes

2021-12-29 13:10 UTC, topirissanen-atoz commented on src/common/components/filter/filter.tsx
> +    if (isModal) {
Cleaned that part of code

2021-12-30 05:53 UTC, jukkah requested changes

2021-12-30 05:53 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +        <Hr />
#45 introduces Separator component. It should be used here as Hr component is removed in that PR too. This needs to be fixed here or in #45 depending on which one will be merged later.

2021-12-30 05:53 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +            onClick={() => setShowModal && setShowModal(false)}
You can also write `setShowModal?.(false)`. I think it might be a little easier to read.

2021-12-30 05:53 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +            onClick={() => setShowModal && setShowModal(false)}
Same here (`setShowModal?.(false)`).

2021-12-30 05:53 UTC, jukkah commented on src/common/components/filter/filter.tsx
> +          {t('vocabulary-filter-filter-list').toUpperCase()}
Use `text-transform: uppercase;` instead here and other places.

2021-12-30 08:56 UTC, jukkah approved these changes

2021-12-30 08:58 UTC, merged