Added id's to interactable components
VRK-YTI/yti-terminology-ui pull request #439
Opened 2023-06-20 08:32 UTC by topirissanen-atoz

Changes in this PR:
-  Added descriptive ID's to interactable components

2023-06-21 10:46 UTC, tomiviljanen commented on datamodel-ui/src/modules/class-form/index.tsx
> +            <Button onClick={() => handleSubmit()} id="submit-butotn">
typo

2023-06-21 10:48 UTC, tomiviljanen requested changes

2023-06-21 10:48 UTC, tomiviljanen commented on datamodel-ui/src/modules/class-form/index.tsx
> +            <Button onClick={() => handleSubmit()} id="submit-butotn">
typo

2023-06-22 05:59 UTC, topirissanen-atoz commented on datamodel-ui/src/modules/class-form/index.tsx
> +            <Button onClick={() => handleSubmit()} id="submit-butotn">
Fixed this

2023-06-22 09:44 UTC, tomiviljanen approved these changes

2023-06-22 09:54 UTC, merged