handle external resources in the list
VRK-YTI/yti-terminology-ui pull request #446
Opened 2023-06-22 11:19 UTC by kkyttala

2023-06-28 04:19 UTC, topirissanen-atoz approved these changes

2023-06-28 05:48 UTC, tomiviljanen approved these changes

2023-06-28 11:57 UTC, tomiviljanen requested changes

2023-06-28 11:57 UTC, tomiviljanen commented on datamodel-ui/src/modules/resource/index.tsx
> +    if (!view.edit || !hasPermission || globalSelected.modelId !== modelId) {
globalselected.modelid !== modelId casuses nothing to render when creating a new attribute or resource since globalselected.modelid is null

2023-06-29 07:18 UTC, tomiviljanen approved these changes

2023-06-29 07:20 UTC, merged