Yti 2887 documentation buttons bugfix
VRK-YTI/yti-terminology-ui pull request #511
Opened 2023-09-06 10:42 UTC by topirissanen-atoz

Changes in this PR:
- Bug with editing buttons not working in new data models documentation tab fixed
- Added support for image rendering to markdown preview

2023-09-06 11:33 UTC, kkyttala requested changes

2023-09-06 11:33 UTC, kkyttala commented on datamodel-ui/src/modules/documentation/index.tsx
> +            : ''
Isn't that redundant to check startsWith? If the purpose is to force https protocol, it might be simpler to define
src={props.src.replace('http://', 'https://')}

2023-09-07 04:11 UTC, topirissanen-atoz commented on datamodel-ui/src/modules/documentation/index.tsx
> +            : ''
A simpler solution added

2023-09-07 05:02 UTC, kkyttala approved these changes

2023-09-07 05:16 UTC, tomiviljanen approved these changes

2023-09-07 05:23 UTC, merged