Small fixes
VRK-YTI/yti-terminology-ui pull request #55
Opened 2022-01-11 11:25 UTC by jukkah

Remove yarn.lock as it's not needed anymore and fix some small bugs.

Refactor also date formatter to use dayjs library. (Dayjs is a small library with no deps.) This way correct format was much easier to achieve. And code readability is also better.

YTI-1629

2022-01-11 12:52 UTC, topirissanen-atoz approved these changes

2022-01-11 17:57 UTC, urhot requested changes

2022-01-11 17:57 UTC, urhot commented on src/common/components/formatted-date/formattted-date.test.tsx
> +import React from 'react';
`formattted-date.test.tsx` → `formatted-date.test.tsx`

2022-01-21 13:04 UTC, kkyttala approved these changes

2022-01-24 09:09 UTC, merged