Yti 1660 terminology pagination
VRK-YTI/yti-terminology-ui pull request #69
Opened 2022-01-31 12:40 UTC by topirissanen-atoz

2022-02-01 06:54 UTC, jukkah requested changes

2022-02-01 06:54 UTC, jukkah commented on src/common/components/pagination/pagination.tsx
> +      query.push(parsedRoute + `?page=${i}${q ? `&q=${q}` : ''}`);
I think, this will reset all other query parameters like filters.

2022-02-01 06:54 UTC, jukkah commented on src/common/components/pagination/pagination.tsx
> +      query.push(query.route + `?page=${i}${q ? `&q=${q}` : ''}`);
Same here.

2022-02-01 06:54 UTC, jukkah commented on src/common/components/search-results/search-results.tsx
> +                      {getPropertyValue({ property: collection.properties.prefLabel, language: i18n.language })
This whole expression looks pretty much the same as `<PropertyValue property={collection.properties.prefLabel} fallbackLanguage="fi" />`.

2022-02-01 06:54 UTC, jukkah commented on src/common/components/search-results/search-results.tsx
> +                  {getPropertyValue({ property: collection.properties.definition })
This looks like pretty much the same as `<PropertyValue property={collection.properties.definition} fallback={t('vocabulary-results-no-description')} />`. That fallback prop does not exist yet, but it is easy to implement.

2022-02-01 06:54 UTC, jukkah commented on src/modules/vocabulary/index.tsx
> +  if (query.query.page && query.query.page !== '1') {
Why `query.query.page` is used here as `page` is already defined on line 46?

2022-02-01 06:54 UTC, jukkah commented on src/modules/vocabulary/index.tsx
> +    if (query.query.page && query.query.page !== '1') {
Same here.

2022-02-01 09:31 UTC, topirissanen-atoz commented on src/common/components/pagination/pagination.tsx
> +      query.push(parsedRoute + `?page=${i}${q ? `&q=${q}` : ''}`);
This won't change state of filter, because the page doesn't refresh and the value of "q" stays the same. That's still the only query parameter that handles filter's state.

2022-02-02 06:27 UTC, jukkah approved these changes

2022-02-02 08:37 UTC, kkyttala commented on src/common/components/search-results/search-results.tsx
> +            const minId = page ? parseInt(page) * 10 - 10 : 0;
Should radix be included here `parseInt(page, 10)`?

Optionally we could use parseInt provided by [lodash](https://lodash.com/docs/#parseInt), where default value 10

2022-02-02 09:05 UTC, topirissanen-atoz commented on src/common/components/search-results/search-results.tsx
> +            const minId = page ? parseInt(page) * 10 - 10 : 0;
This has been fixed in the upcoming push.

2022-02-07 06:37 UTC, jukkah approved these changes

2022-02-07 12:46 UTC, merged