Yti 1669 definition html links
VRK-YTI/yti-terminology-ui pull request #77
Opened 2022-02-16 13:35 UTC by topirissanen-atoz

2022-02-17 13:12 UTC, kkyttala requested changes

2022-02-17 13:12 UTC, kkyttala commented on src/common/components/text-links/index.tsx
> +    if (child.nodeName.toLowerCase().includes('a')) {
Is this an appropriate way to check node name? This will match if node's name contains `a`, e.g. span,

2022-02-18 06:29 UTC, topirissanen-atoz commented on src/common/components/text-links/index.tsx
> +    if (child.nodeName.toLowerCase().includes('a')) {
Didn't take that into consideration. I will change this to be strict check for `a` elements.

2022-02-18 06:34 UTC, jukkah requested changes

2022-02-18 06:34 UTC, jukkah commented on src/common/components/text-links/index.tsx
> +function ParseText({ text, t }: ParseTextProps) {
Don't pass `t` as a prop. Either call useTranslation here or pass translated text as a prop. This is because of if we want to use extractor (or find undefined/unused translations) some day, this way it will skip definition of `link-opens-new-window-external`.

2022-02-18 06:42 UTC, jukkah approved these changes

2022-02-23 13:48 UTC, merged