Yti 1668 translation bugs
VRK-YTI/yti-terminology-ui pull request #80
Opened 2022-02-21 10:47 UTC by topirissanen-atoz

2022-02-22 10:46 UTC, kkyttala approved these changes

2022-02-25 06:47 UTC, jukkah requested changes

2022-02-25 06:47 UTC, jukkah commented on src/modules/concept/index.tsx
> +            {conceptTitles
I think conditional rendering is redundant here as PropertyValue doesn't render anything if property is []. This also requires that conceptTitles !== undefined. I think it would be fixed on line 45 by adding `?? []` there.

2022-03-01 07:40 UTC, jukkah approved these changes

2022-03-01 13:26 UTC, merged